package com.driveflix.app;

import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.media.AudioManager;import android.net.*;import android.os.*;import android.view.*;import android.view.WindowManager;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.core.view.*;import androidx.media3.common.C;import androidx.media3.common.MediaItem;import androidx.media3.common.MimeTypes;import androidx.media3.common.PlaybackParameters;import androidx.media3.exoplayer.ExoPlayer;import androidx.media3.ui.PlayerView;import java.util.*;

public class PlayerActivity extends AppCompatActivity{
 ExoPlayer player;String id,url,sub,title;TextView overlay;AudioManager audio;int maxVol,startVol;float startY,startBrightness,scale=1f;boolean verticalGesture=false;Handler handler=new Handler(Looper.getMainLooper());PlayerView playerView;GestureDetector gestureDetector;ScaleGestureDetector scaleGestureDetector;Runnable sleepTask;float[] speeds=new float[]{0.5f,0.75f,1f,1.25f,1.5f,2f};int speedIndex=2;
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_player);immersive();id=getIntent().getStringExtra("id");url=getIntent().getStringExtra("url");sub=getIntent().getStringExtra("subtitle");title=getIntent().getStringExtra("title");overlay=findViewById(R.id.gestureOverlay);audio=(AudioManager)getSystemService(AUDIO_SERVICE);maxVol=audio.getStreamMaxVolume(AudioManager.STREAM_MUSIC);playerView=findViewById(R.id.playerView);playerView.setUseController(true);playerView.setControllerAutoShow(true);playerView.setControllerHideOnTouch(false);player=new ExoPlayer.Builder(this).build();playerView.setPlayer(player);setupGestures();playerView.setOnTouchListener((v,e)->{scaleGestureDetector.onTouchEvent(e);gestureDetector.onTouchEvent(e);return handleVerticalGesture(v,e);});findViewById(R.id.timerBtn).setOnClickListener(v->showSleepDialog());MediaItem.Builder mb=new MediaItem.Builder().setUri(Uri.parse(url)).setMediaMetadata(new androidx.media3.common.MediaMetadata.Builder().setTitle(title).build());if(sub!=null&&!sub.isEmpty()){MediaItem.SubtitleConfiguration sc=new MediaItem.SubtitleConfiguration.Builder(Uri.parse(sub)).setMimeType(sub.toLowerCase().endsWith(".vtt")?MimeTypes.TEXT_VTT:MimeTypes.APPLICATION_SUBRIP).setLanguage("en").setSelectionFlags(C.SELECTION_FLAG_DEFAULT).build();mb.setSubtitleConfigurations(Collections.singletonList(sc));}player.setMediaItem(mb.build());player.prepare();long p=Prefs.pos(this,id);if(p>0)player.seekTo(p);player.play();}
 void immersive(){WindowCompat.setDecorFitsSystemWindows(getWindow(),false);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);View d=getWindow().getDecorView();d.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);} 
 void setupGestures(){gestureDetector=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){public boolean onDown(MotionEvent e){return true;}public boolean onDoubleTap(MotionEvent e){if(player==null)return true;int w=playerView.getWidth();long pos=player.getCurrentPosition();if(e.getX()<w/2f){player.seekTo(Math.max(0,pos-10000));showOverlay("⏪ 10 sec");}else{player.seekTo(pos+10000);showOverlay("10 sec ⏩");}hideOverlaySoon();return true;}public boolean onSingleTapConfirmed(MotionEvent e){toggleControls();return true;}});scaleGestureDetector=new ScaleGestureDetector(this,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){scale*=d.getScaleFactor();scale=clamp(scale,1f,2.5f);playerView.setScaleX(scale);playerView.setScaleY(scale);showOverlay(scale<=1.05f?"Fit":"Zoom "+(int)(scale*100)+"%");hideOverlaySoon();return true;}});} 
 void toggleControls(){View top=findViewById(R.id.playerTopControls);boolean visible=top.getVisibility()==View.VISIBLE&&playerView.isControllerFullyVisible();if(visible){top.setVisibility(View.GONE);playerView.hideController();}else{top.setVisibility(View.VISIBLE);playerView.showController();}} 
 boolean handleVerticalGesture(View v,MotionEvent e){int w=v.getWidth();switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:verticalGesture=e.getX()<w*0.25f||e.getX()>w*0.75f;if(!verticalGesture)return false;startY=e.getY();startVol=audio.getStreamVolume(AudioManager.STREAM_MUSIC);WindowManager.LayoutParams lp=getWindow().getAttributes();startBrightness=lp.screenBrightness<0?0.5f:lp.screenBrightness;return true;case MotionEvent.ACTION_MOVE:if(!verticalGesture||e.getPointerCount()>1)return false;float diff=(startY-e.getY())/Math.max(1f,v.getHeight());if(e.getX()<w/2f){float b=clamp(startBrightness+diff,0.02f,1f);WindowManager.LayoutParams blp=getWindow().getAttributes();blp.screenBrightness=b;getWindow().setAttributes(blp);showOverlay("Brightness " +(int)(b*100)+"%");}else{int nv=(int)clamp(startVol+(diff*maxVol),0,maxVol);audio.setStreamVolume(AudioManager.STREAM_MUSIC,nv,0);showOverlay("Volume "+(int)((nv*100f)/maxVol)+"%");}return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:if(!verticalGesture)return false;hideOverlaySoon();verticalGesture=false;return true;}return false;}
 void showSpeedDialog(){String[] items={"0.5x","0.75x","1x Normal","1.25x","1.5x","2x"};new AlertDialog.Builder(this).setTitle("Playback speed").setItems(items,(d,which)->{speedIndex=which;float s=speeds[which];player.setPlaybackParameters(new PlaybackParameters(s));showOverlay("Speed "+items[which]);hideOverlaySoon();}).show();}
 void showSleepDialog(){String[] items={"Off","15 minutes","30 minutes","60 minutes","End of current movie"};new AlertDialog.Builder(this).setTitle("Sleep timer").setItems(items,(d,which)->{if(sleepTask!=null)handler.removeCallbacks(sleepTask);if(which==0){showOverlay("Sleep timer off");hideOverlaySoon();return;}long delay=which==1?15*60000L:which==2?30*60000L:which==3?60*60000L:Math.max(60000L,player.getDuration()-player.getCurrentPosition());sleepTask=()->{if(player!=null){Prefs.pos(this,id,player.getCurrentPosition());player.pause();finish();}};handler.postDelayed(sleepTask,delay);showOverlay("Sleep timer set");hideOverlaySoon();}).show();}
 float clamp(float v,float min,float max){return Math.max(min,Math.min(max,v));}
 void showOverlay(String s){overlay.setText(s);overlay.setVisibility(View.VISIBLE);} void hideOverlaySoon(){overlay.removeCallbacks(null);overlay.postDelayed(()->overlay.setVisibility(View.GONE),900);} 
 protected void onResume(){super.onResume();immersive();}
 protected void onPause(){super.onPause();if(player!=null)Prefs.pos(this,id,player.getCurrentPosition());}
 protected void onDestroy(){if(sleepTask!=null)handler.removeCallbacks(sleepTask);if(player!=null){Prefs.pos(this,id,player.getCurrentPosition());player.release();}super.onDestroy();}
}
